### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by iansetliff** [mozack/vdjician#1]
Upon running on sorted bam file (113.9 mb file, on which I can run samtools flagstat), I always get a segmentation fault error. 

$VDJER --in in.bam --rl 50 --t 8 --ins 216 --chain IGH --ref-dir $VDJER_REF_DIR > vdjer.sam 2> vdjer.log

Last line on vdjer.log is "Extracting reads..."

If you need any more details, please let me know.

**Comment by mozack** [comment]
Run samtools index on the input bam file and retry.

**Comment by mozack** [comment]
Also, in the latest release the --rl param is not necessary.

**Comment by iansetliff** [comment]
Thanks! My fault for not indexing -- it says it clearly in the readme and I neglected it.

Thanks again.
