### ISSUE TITLE
Post processing light chains

### ISSUE THREAD

**Issue by mbaddoo** [mozack/vdjician#14]
Hello!  Thank you for this tool.  I attempted post-processing using the scripts and was met the following error when I set the argument to "no" for light chains:

read_count_file = sys.argv[7]
IndexError:  list index out of range

I did not have this issue when I performed post-processing on the heavy chain.  Might you be able to help me sort our this error, please?

Many thanks!

**Comment by mozack** [comment]
Please post the exact command you are running.

**Comment by mbaddoo** [comment]
Sure.  See command line below:

python /Applications/NGS/Toolbox/vdjer-master/post_process/collect_vdjer_stats.py igk_all_sequences.fa no final_inventory.txt /Volumes/Flemington_lab_experiments/Hani_SingleCellSeq_09272016/proj_ptcl/data/kucuk/3_vdjer_and_rsem_output/results/HighV-QUEST_output/Kucuk_IGK/1_Summary.txt igk igk_read_counts.txt | python /Applications/NGS/Toolbox/vdjer-master/post_process/cluster_results.py > kucuk_igk.txt
Traceback (most recent call last):
  File "/Applications/NGS/Toolbox/vdjer-master/post_process/collect_vdjer_stats.py", line 9, in <module>
    read_count_file = sys.argv[7]
IndexError: list index out of range

Thank you!

**Comment by mozack** [comment]
Looks like you're missing the RESULT_DIR

**Comment by mbaddoo** [comment]
Aaaaack!!! My sincere apologies for troubling you over such a mistake. Working perfectly now. Thanks very much for your reply!
Best-
Melody
