### ISSUE TITLE
VDJER extracts no clones on bam file produced with STAR

### ISSUE THREAD

**Issue by PoslavskySV** [mozack/vdjician#2]
Hi,

I'm trying to run vdjer on bam files obtained with STAR and get zero clones even on the sample data which is in the demo folder. For example, for the file `star.sort.bam` from `demo/` folder I do the following:

```
samtools fastq star.sort.bam > data.fastq
STAR --runThreadN 42 --genomeDir gencode_hg38/ --readFilesIn data.fastq --outSAMtype BAM SortedByCoordinate --outSAMunmapped Within --outStd BAM_SortedByCoordinate > data.sort.bam
samtools index data.sort.bam
vdjer --in data.sort.bam --rl 50 --ins 175 --chain IGH --ref-dir ~/local/vdjer/reference/igh > vdjer.sam 2>log 
```

As result vdjer returns zero clones, but with the original bam file `vdjer` works fine and produces a lot of clones as expected. In the log produced by vdjer there are lines:

```
Extracting reads...
primary_reads size1: [74341]
secondary_reads size1: [50130]
primary_output1: [0] primary_output2: [0] secondary_output1: [0] secondary_output2: [0]
```

It seems that all zeros in the last line is not good. 

I use STAR version 2.4.2a (but I also tried 2.5.2b) and reference downloaded from http://www.gencodegenes.org/releases/current.html (GRCh38.p7 ALL and Comprehensive gene annotation GTF) which I build with:

```
STAR --runMode genomeGenerate --runThreadN 52 --genomeDir gencode_hg38/ --genomeFastaFiles GRCh38.p7.genome.fa --sjdbGTFfile gencode.v25.chr_patch_hapl_scaff.annotation.gtf
```

What I'm doing wrong? Maybe `vdjer` requires another STAR reference?

**Comment by mozack** [comment]
Hi,

I see two issues here.

1) This is paired end data (V'DJer only supports paired end data).  You'll want to convert the BAM to 2 paired end fastq files.

2) The ALL reference includes ALT contigs and STAR is not yet ALT aware.  It is possible that this may cause issues and we have not tested against a reference including the alternate contigs.  I recommend using the primary (PRI) assembly.

**Comment by PoslavskySV** [comment]
Thanks! I missed that vdjer supports only paired end data. Now, when I've extracted 2 fastq files from star.sort.bam, all worked fine! And for further analysis I will use PRI assembly.
