### ISSUE TITLE
STAR 1-pass vs 2-pass

### ISSUE THREAD

**Issue by PoslavskySV** [mozack/vdjician#4]
Hi, 

Is it important which STAR pipeline (1-pass or 2-pass) to use for further processing with VDJer? 

Thanks!

**Comment by mozack** [comment]
In our simulated testing, the results were essentially equivalent between 1-pass and 2-pass.  We are using 1-pass for our analyses.

**Comment by PoslavskySV** [comment]
Thanks for the answer!
