### ISSUE TITLE
Core dump while running bam files

### ISSUE THREAD

**Issue by harrydgnt** [mozack/vdjician#5]
Hello 

I was trying to use vdjer but I kept getting into error.

Below is the core dump error and log files. 

/work/UGE/8.0.1/hoffman2/spool/n6261/job_scripts/929296: line 1: 17148 Aborted                 (core dumped) ./vdjer --in /u/home/h/harryyan/project-eeskin/utilities/vdjer-0.12/G19324.GTEX-S341-0326-SM-2XCAU.1.bam --t 4 --ins 175 --chain IGH --ref-dir /u/home/h/harryyan/project-eeskin/utilities/vdjer-0.12/db/igh > test.sam 2> test.log

`[harryyan@login3 vdjer-0.12]$ cat test.log
ELAPSED_SECS	START	0	0
PROC_STATUS	START	Name:	vdjer
PROC_STATUS	START	State:	R (running)
PROC_STATUS	START	Tgid:	17148
PROC_STATUS	START	Pid:	17148
PROC_STATUS	START	PPid:	17147
PROC_STATUS	START	TracerPid:	0
PROC_STATUS	START	Uid:	11493	11493	11493	11493
PROC_STATUS	START	Gid:	8164	8164	8164	8164
PROC_STATUS	START	Utrace:	0
PROC_STATUS	START	FDSize:	256
PROC_STATUS	START	Groups:	8164 62342
PROC_STATUS	START	VmPeak:	   19096 kB
PROC_STATUS	START	VmSize:	   19096 kB
PROC_STATUS	START	VmLck:	       0 kB
PROC_STATUS	START	VmHWM:	    1472 kB
PROC_STATUS	START	VmRSS:	    1472 kB
PROC_STATUS	START	VmData:	    2264 kB
PROC_STATUS	START	VmStk:	      96 kB
PROC_STATUS	START	VmExe:	     944 kB
PROC_STATUS	START	VmLib:	    3420 kB
PROC_STATUS	START	VmPTE:	      56 kB
PROC_STATUS	START	VmSwap:	       0 kB
PROC_STATUS	START	Threads:	1
PROC_STATUS	START	SigQ:	0/193442
PROC_STATUS	START	SigPnd:	0000000000000000
PROC_STATUS	START	ShdPnd:	0000000000000000
PROC_STATUS	START	SigBlk:	0000000000000000
PROC_STATUS	START	SigIgn:	0000000000000000
PROC_STATUS	START	SigCgt:	0000000180000000
PROC_STATUS	START	CapInh:	0000000000000000
PROC_STATUS	START	CapPrm:	0000000000000000
PROC_STATUS	START	CapEff:	0000000000000000
PROC_STATUS	START	CapBnd:	ffffffffffffffff
PROC_STATUS	START	Cpus_allowed:	ffffffff
PROC_STATUS	START	Cpus_allowed_list:	0-31
PROC_STATUS	START	Mems_allowed:	00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000003
PROC_STATUS	START	Mems_allowed_list:	0-1
PROC_STATUS	START	voluntary_ctxt_switches:	22
PROC_STATUS	START	nonvoluntary_ctxt_switches:	2
BUDDY_INFO	START	Node 0, zone      DMA      3      2      2      1      2      1      0      0      1      1      3
BUDDY_INFO	START	Node 0, zone    DMA32    681    632    506    304    186    120    134     64     43     60    733
BUDDY_INFO	START	Node 0, zone   Normal   9658  10031   5043   5620   5978   4392   2999   2068   1541   1648    426
BUDDY_INFO	START	Node 1, zone   Normal   9695  21256  17926  11515  20274  10822   8944   4658   3728   1323    190
STAT:1478159295	START	17148 (vdjer) R 17147 17147 17147 0 -1 4202496 508 0 2 0 0 0 0 0 20 0 1 0 512859146 19554304 370 18446744073709551615 4194304 5160238 140729453823936 140729453812664 48002282497280 0 0 0 0 0 0 0 17 5 0 0 0 0 0
input	/u/home/h/harryyan/project-eeskin/utilities/vdjer-0.12/G19324.GTEX-S341-0326-SM-2XCAU.1.bam
min node freq	3
min base qual	90
min contig score (log scaled)	-5.000000
num threads	4
v anchor file	/u/home/h/harryyan/project-eeskin/utilities/vdjer-0.12/db/igh/v_index
j anchor file	/u/home/h/harryyan/project-eeskin/utilities/vdjer-0.12/db/igh/j_index
max anchor mismatches:	4
min V/J window	10
max V/J window	90
conserved J AA	87
total untrimmed contig length	486
extension beyond conserved J AA	162
fasta file containing functional V/D/J sequences	/u/home/h/harryyan/project-eeskin/utilities/vdjer-0.12/db/igh/ig_vdj.fa
variable region locus	chr14:105566277-106879844
constant region locus	chr14:105566277-105939754
median insert length	175
read coverage floor for contig filtering	1
kmer	35
source node similarity file	/u/home/h/harryyan/project-eeskin/utilities/vdjer-0.12/db/igh/v_region.fa
vregion kmer size	15
minimum homology score for source nodes	30
span for read base filtering	35
span for mate base filtering	48
start point for contig filtering	52
stop point for contig filtering	411
window overlap check size	320
read length:	76Loading vmers
Loading jmers
ELAPSED_SECS	POST_VJF_INIT	13	13
PROC_STATUS	POST_VJF_INIT	Name:	vdjer
PROC_STATUS	POST_VJF_INIT	State:	R (running)
PROC_STATUS	POST_VJF_INIT	Tgid:	17148
PROC_STATUS	POST_VJF_INIT	Pid:	17148
PROC_STATUS	POST_VJF_INIT	PPid:	17147
PROC_STATUS	POST_VJF_INIT	TracerPid:	0
PROC_STATUS	POST_VJF_INIT	Uid:	11493	11493	11493	11493
PROC_STATUS	POST_VJF_INIT	Gid:	8164	8164	8164	8164
PROC_STATUS	POST_VJF_INIT	Utrace:	0
PROC_STATUS	POST_VJF_INIT	FDSize:	256
PROC_STATUS	POST_VJF_INIT	Groups:	8164 62342
PROC_STATUS	POST_VJF_INIT	VmPeak:	  289180 kB
PROC_STATUS	POST_VJF_INIT	VmSize:	  256408 kB
PROC_STATUS	POST_VJF_INIT	VmLck:	       0 kB
PROC_STATUS	POST_VJF_INIT	VmHWM:	  245144 kB
PROC_STATUS	POST_VJF_INIT	VmRSS:	  212496 kB
PROC_STATUS	POST_VJF_INIT	VmData:	  239576 kB
PROC_STATUS	POST_VJF_INIT	VmStk:	      96 kB
PROC_STATUS	POST_VJF_INIT	VmExe:	     944 kB
PROC_STATUS	POST_VJF_INIT	VmLib:	    3420 kB
PROC_STATUS	POST_VJF_INIT	VmPTE:	     480 kB
PROC_STATUS	POST_VJF_INIT	VmSwap:	       0 kB
PROC_STATUS	POST_VJF_INIT	Threads:	1
PROC_STATUS	POST_VJF_INIT	SigQ:	0/193442
PROC_STATUS	POST_VJF_INIT	SigPnd:	0000000000000000
PROC_STATUS	POST_VJF_INIT	ShdPnd:	0000000000000000
PROC_STATUS	POST_VJF_INIT	SigBlk:	0000000000000000
PROC_STATUS	POST_VJF_INIT	SigIgn:	0000000000000000
PROC_STATUS	POST_VJF_INIT	SigCgt:	0000000180000000
PROC_STATUS	POST_VJF_INIT	CapInh:	0000000000000000
PROC_STATUS	POST_VJF_INIT	CapPrm:	0000000000000000
PROC_STATUS	POST_VJF_INIT	CapEff:	0000000000000000
PROC_STATUS	POST_VJF_INIT	CapBnd:	ffffffffffffffff
PROC_STATUS	POST_VJF_INIT	Cpus_allowed:	ffffffff
PROC_STATUS	POST_VJF_INIT	Cpus_allowed_list:	0-31
PROC_STATUS	POST_VJF_INIT	Mems_allowed:	00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000003
PROC_STATUS	POST_VJF_INIT	Mems_allowed_list:	0-1
PROC_STATUS	POST_VJF_INIT	voluntary_ctxt_switches:	53
PROC_STATUS	POST_VJF_INIT	nonvoluntary_ctxt_switches:	1320
BUDDY_INFO	POST_VJF_INIT	Node 0, zone      DMA      3      2      2      1      2      1      0      0      1      1      3
BUDDY_INFO	POST_VJF_INIT	Node 0, zone    DMA32    681    632    506    304    186    120    134     64     43     60    733
BUDDY_INFO	POST_VJF_INIT	Node 0, zone   Normal    745   9655   5054   1493   2178   4400   3008   2076   1544   1563    426
BUDDY_INFO	POST_VJF_INIT	Node 1, zone   Normal   6323  21296  17943  11521  20041  10823   8944   4658   3728   1322    190
STAT:1478159308	POST_VJF_INIT	17148 (vdjer) R 17147 17147 17147 0 -1 4202496 22341 0 2 0 1218 32 0 0 20 0 1 0 512859146 262561792 53124 18446744073709551615 4194304 5160238 140729453823936 140729453821848 48002282497280 0 0 0 0 0 0 0 17 0 0 0 36 0 0
Extracting reads...
primary_reads size1: [0]
secondary_reads size1: [0]
Increasing read_name bufIncreasing read_name bufIncreasing read_name bufIncreasing read_name bufprimary_output1: [254182] primary_output2: [254182] secondary_output1: [12595706] secondary_output2: [12595706]
Read extract done...
ELAPSED_SECS	POST_READ_EXTRACT	2220	2207
PROC_STATUS	POST_READ_EXTRACT	Name:	vdjer
PROC_STATUS	POST_READ_EXTRACT	State:	R (running)
PROC_STATUS	POST_READ_EXTRACT	Tgid:	17148
PROC_STATUS	POST_READ_EXTRACT	Pid:	17148
PROC_STATUS	POST_READ_EXTRACT	PPid:	17147
PROC_STATUS	POST_READ_EXTRACT	TracerPid:	0
PROC_STATUS	POST_READ_EXTRACT	Uid:	11493	11493	11493	11493
PROC_STATUS	POST_READ_EXTRACT	Gid:	8164	8164	8164	8164
PROC_STATUS	POST_READ_EXTRACT	Utrace:	0
PROC_STATUS	POST_READ_EXTRACT	FDSize:	256
PROC_STATUS	POST_READ_EXTRACT	Groups:	8164 62342
PROC_STATUS	POST_READ_EXTRACT	VmPeak:	16536692 kB
PROC_STATUS	POST_READ_EXTRACT	VmSize:	15749272 kB
PROC_STATUS	POST_READ_EXTRACT	VmLck:	       0 kB
PROC_STATUS	POST_READ_EXTRACT	VmHWM:	16390668 kB
PROC_STATUS	POST_READ_EXTRACT	VmRSS:	15603908 kB
PROC_STATUS	POST_READ_EXTRACT	VmData:	15732440 kB
PROC_STATUS	POST_READ_EXTRACT	VmStk:	      96 kB
PROC_STATUS	POST_READ_EXTRACT	VmExe:	     944 kB
PROC_STATUS	POST_READ_EXTRACT	VmLib:	    3420 kB
PROC_STATUS	POST_READ_EXTRACT	VmPTE:	   30552 kB
PROC_STATUS	POST_READ_EXTRACT	VmSwap:	       0 kB
PROC_STATUS	POST_READ_EXTRACT	Threads:	1
PROC_STATUS	POST_READ_EXTRACT	SigQ:	0/193442
PROC_STATUS	POST_READ_EXTRACT	SigPnd:	0000000000000000
PROC_STATUS	POST_READ_EXTRACT	ShdPnd:	0000000000000000
PROC_STATUS	POST_READ_EXTRACT	SigBlk:	0000000000000000
PROC_STATUS	POST_READ_EXTRACT	SigIgn:	0000000000000000
PROC_STATUS	POST_READ_EXTRACT	SigCgt:	0000000180000000
PROC_STATUS	POST_READ_EXTRACT	CapInh:	0000000000000000
PROC_STATUS	POST_READ_EXTRACT	CapPrm:	0000000000000000
PROC_STATUS	POST_READ_EXTRACT	CapEff:	0000000000000000
PROC_STATUS	POST_READ_EXTRACT	CapBnd:	ffffffffffffffff
PROC_STATUS	POST_READ_EXTRACT	Cpus_allowed:	ffffffff
PROC_STATUS	POST_READ_EXTRACT	Cpus_allowed_list:	0-31
PROC_STATUS	POST_READ_EXTRACT	Mems_allowed:	00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000003
PROC_STATUS	POST_READ_EXTRACT	Mems_allowed_list:	0-1
PROC_STATUS	POST_READ_EXTRACT	voluntary_ctxt_switches:	71
PROC_STATUS	POST_READ_EXTRACT	nonvoluntary_ctxt_switches:	225040
BUDDY_INFO	POST_READ_EXTRACT	Node 0, zone      DMA      3      2      2      1      2      1      0      0      1      1      3
BUDDY_INFO	POST_READ_EXTRACT	Node 0, zone    DMA32    681    632    508    302    184    118    134     63     42      1      0
BUDDY_INFO	POST_READ_EXTRACT	Node 0, zone   Normal  14391  10954   4339   1305    436    173   1411   2056   1544     39    111
BUDDY_INFO	POST_READ_EXTRACT	Node 1, zone   Normal    410    238    414    151    111     67    101     54   1898    127      0
STAT:1478161515	POST_READ_EXTRACT	17148 (vdjer) R 17147 17147 17147 0 -1 4202496 1832231 0 2 0 220254 1632 0 0 20 0 1 0 512859146 16127254528 3900977 18446744073709551615 4194304 5160238 140729453823936 140729453823432 48002282497280 0 0 0 0 0 0 0 17 5 0 0 36 0 0
Assembling...
Assembling: ->
ELAPSED_SECS	PRE_PRE_GRAPH1	2220	0
PROC_STATUS	PRE_PRE_GRAPH1	Name:	vdjer
PROC_STATUS	PRE_PRE_GRAPH1	State:	R (running)
PROC_STATUS	PRE_PRE_GRAPH1	Tgid:	17148
PROC_STATUS	PRE_PRE_GRAPH1	Pid:	17148
PROC_STATUS	PRE_PRE_GRAPH1	PPid:	17147
PROC_STATUS	PRE_PRE_GRAPH1	TracerPid:	0
PROC_STATUS	PRE_PRE_GRAPH1	Uid:	11493	11493	11493	11493
PROC_STATUS	PRE_PRE_GRAPH1	Gid:	8164	8164	8164	8164
PROC_STATUS	PRE_PRE_GRAPH1	Utrace:	0
PROC_STATUS	PRE_PRE_GRAPH1	FDSize:	256
PROC_STATUS	PRE_PRE_GRAPH1	Groups:	8164 62342
PROC_STATUS	PRE_PRE_GRAPH1	VmPeak:	16536692 kB
PROC_STATUS	PRE_PRE_GRAPH1	VmSize:	15749272 kB
PROC_STATUS	PRE_PRE_GRAPH1	VmLck:	       0 kB
PROC_STATUS	PRE_PRE_GRAPH1	VmHWM:	16390668 kB
PROC_STATUS	PRE_PRE_GRAPH1	VmRSS:	15603916 kB
PROC_STATUS	PRE_PRE_GRAPH1	VmData:	15732440 kB
PROC_STATUS	PRE_PRE_GRAPH1	VmStk:	      96 kB
PROC_STATUS	PRE_PRE_GRAPH1	VmExe:	     944 kB
PROC_STATUS	PRE_PRE_GRAPH1	VmLib:	    3420 kB
PROC_STATUS	PRE_PRE_GRAPH1	VmPTE:	   30552 kB
PROC_STATUS	PRE_PRE_GRAPH1	VmSwap:	       0 kB
PROC_STATUS	PRE_PRE_GRAPH1	Threads:	1
PROC_STATUS	PRE_PRE_GRAPH1	SigQ:	0/193442
PROC_STATUS	PRE_PRE_GRAPH1	SigPnd:	0000000000000000
PROC_STATUS	PRE_PRE_GRAPH1	ShdPnd:	0000000000000000
PROC_STATUS	PRE_PRE_GRAPH1	SigBlk:	0000000000000000
PROC_STATUS	PRE_PRE_GRAPH1	SigIgn:	0000000000000000
PROC_STATUS	PRE_PRE_GRAPH1	SigCgt:	0000000180000000
PROC_STATUS	PRE_PRE_GRAPH1	CapInh:	0000000000000000
PROC_STATUS	PRE_PRE_GRAPH1	CapPrm:	0000000000000000
PROC_STATUS	PRE_PRE_GRAPH1	CapEff:	0000000000000000
PROC_STATUS	PRE_PRE_GRAPH1	CapBnd:	ffffffffffffffff
PROC_STATUS	PRE_PRE_GRAPH1	Cpus_allowed:	ffffffff
PROC_STATUS	PRE_PRE_GRAPH1	Cpus_allowed_list:	0-31
PROC_STATUS	PRE_PRE_GRAPH1	Mems_allowed:	00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000003
PROC_STATUS	PRE_PRE_GRAPH1	Mems_allowed_list:	0-1
PROC_STATUS	PRE_PRE_GRAPH1	voluntary_ctxt_switches:	71
PROC_STATUS	PRE_PRE_GRAPH1	nonvoluntary_ctxt_switches:	225040
BUDDY_INFO	PRE_PRE_GRAPH1	Node 0, zone      DMA      3      2      2      1      2      1      0      0      1      1      3
BUDDY_INFO	PRE_PRE_GRAPH1	Node 0, zone    DMA32    681    632    508    302    184    118    134     63     42      1      0
BUDDY_INFO	PRE_PRE_GRAPH1	Node 0, zone   Normal  14391  10954   4339   1305    436    173   1411   2056   1544     39    111
BUDDY_INFO	PRE_PRE_GRAPH1	Node 1, zone   Normal    410    238    414    151    111     67    101     54   1898    127      0
STAT:1478161515	PRE_PRE_GRAPH1	17148 (vdjer) R 17147 17147 17147 0 -1 4202496 1832237 0 2 0 220254 1632 0 0 20 0 1 0 512859146 16127254528 3900980 18446744073709551615 4194304 5160238 140729453823936 140729453823432 48002282497280 0 0 0 0 0 0 0 17 5 0 0 36 0 0
input_len: 155559384, record_len: 153
pre_record_count: 1000000
Pre Num reads: 1016728
Pre Num nodes: 5275986
ELAPSED_SECS	PRE_PRE_GRAPH2	2261	41
PROC_STATUS	PRE_PRE_GRAPH2	Name:	vdjer
PROC_STATUS	PRE_PRE_GRAPH2	State:	R (running)
PROC_STATUS	PRE_PRE_GRAPH2	Tgid:	17148
PROC_STATUS	PRE_PRE_GRAPH2	Pid:	17148
PROC_STATUS	PRE_PRE_GRAPH2	PPid:	17147
PROC_STATUS	PRE_PRE_GRAPH2	TracerPid:	0
PROC_STATUS	PRE_PRE_GRAPH2	Uid:	11493	11493	11493	11493
PROC_STATUS	PRE_PRE_GRAPH2	Gid:	8164	8164	8164	8164
PROC_STATUS	PRE_PRE_GRAPH2	Utrace:	0
PROC_STATUS	PRE_PRE_GRAPH2	FDSize:	256
PROC_STATUS	PRE_PRE_GRAPH2	Groups:	8164 62342
PROC_STATUS	PRE_PRE_GRAPH2	VmPeak:	17528048 kB
PROC_STATUS	PRE_PRE_GRAPH2	VmSize:	16938224 kB
PROC_STATUS	PRE_PRE_GRAPH2	VmLck:	       0 kB
PROC_STATUS	PRE_PRE_GRAPH2	VmHWM:	17382612 kB
PROC_STATUS	PRE_PRE_GRAPH2	VmRSS:	16792784 kB
PROC_STATUS	PRE_PRE_GRAPH2	VmData:	16921392 kB
PROC_STATUS	PRE_PRE_GRAPH2	VmStk:	      96 kB
PROC_STATUS	PRE_PRE_GRAPH2	VmExe:	     944 kB
PROC_STATUS	PRE_PRE_GRAPH2	VmLib:	    3420 kB
PROC_STATUS	PRE_PRE_GRAPH2	VmPTE:	   32876 kB
PROC_STATUS	PRE_PRE_GRAPH2	VmSwap:	       0 kB
PROC_STATUS	PRE_PRE_GRAPH2	Threads:	1
PROC_STATUS	PRE_PRE_GRAPH2	SigQ:	0/193442
PROC_STATUS	PRE_PRE_GRAPH2	SigPnd:	0000000000000000
PROC_STATUS	PRE_PRE_GRAPH2	ShdPnd:	0000000000000000
PROC_STATUS	PRE_PRE_GRAPH2	SigBlk:	0000000000000000
PROC_STATUS	PRE_PRE_GRAPH2	SigIgn:	0000000000000000
PROC_STATUS	PRE_PRE_GRAPH2	SigCgt:	0000000180000000
PROC_STATUS	PRE_PRE_GRAPH2	CapInh:	0000000000000000
PROC_STATUS	PRE_PRE_GRAPH2	CapPrm:	0000000000000000
PROC_STATUS	PRE_PRE_GRAPH2	CapEff:	0000000000000000
PROC_STATUS	PRE_PRE_GRAPH2	CapBnd:	ffffffffffffffff
PROC_STATUS	PRE_PRE_GRAPH2	Cpus_allowed:	ffffffff
PROC_STATUS	PRE_PRE_GRAPH2	Cpus_allowed_list:	0-31
PROC_STATUS	PRE_PRE_GRAPH2	Mems_allowed:	00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000003
PROC_STATUS	PRE_PRE_GRAPH2	Mems_allowed_list:	0-1
PROC_STATUS	PRE_PRE_GRAPH2	voluntary_ctxt_switches:	71
PROC_STATUS	PRE_PRE_GRAPH2	nonvoluntary_ctxt_switches:	229176
BUDDY_INFO	PRE_PRE_GRAPH2	Node 0, zone      DMA      3      2      2      1      2      1      0      0      1      1      3
BUDDY_INFO	PRE_PRE_GRAPH2	Node 0, zone    DMA32    656    566    430    266    157    105    124     59     44      1      0
BUDDY_INFO	PRE_PRE_GRAPH2	Node 0, zone   Normal   1874   1148    758    482    329    211   1390   1993   1492     41     87
BUDDY_INFO	PRE_PRE_GRAPH2	Node 1, zone   Normal    262    356    434    119     89     67    103     52   1254     72      0
STAT:1478161556	PRE_PRE_GRAPH2	17148 (vdjer) R 17147 17147 17147 0 -1 4202496 2001768 0 2 0 224119 1830 0 0 20 0 1 0 512859146 17344741376 4198196 18446744073709551615 4194304 5160238 140729453823936 140729453812488 48002282497280 0 0 0 0 0 0 0 17 3 0 0 36 0 0
input_len: 7708572072, record_len: 153
pre_record_count: 1000000
pre_record_count: 2000000
pre_record_count: 3000000
pre_record_count: 4000000
pre_record_count: 5000000
pre_record_count: 6000000
pre_record_count: 7000000
pre_record_count: 8000000
pre_record_count: 9000000
pre_record_count: 10000000
vdjer: src/main/c/sparsehash/internal/densehashtable.h:782: void google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::clear_to_size(typename Alloc::rebind<Value>::other::size_type) [with Value = std::pair<const char* const, pre_node>, Key = const char*, HashFcn = my_hash, ExtractKey = google::dense_hash_map<const char*, pre_node, my_hash, eqstr, google::libc_allocator_with_realloc<std::pair<const char* const, pre_node> > >::SelectKey, SetKey = google::dense_hash_map<const char*, pre_node, my_hash, eqstr, google::libc_allocator_with_realloc<std::pair<const char* const, pre_node> > >::SetKey, EqualKey = eqstr, Alloc = google::libc_allocator_with_realloc<std::pair<const char* const, pre_node> >]: Assertion `table' failed.`

Thank you for your help! 

Harry

**Comment by mozack** [comment]
It looks like there was an issue allocating memory.  If you're running on a cluster, you may need to request more RAM.
