### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by afonsoguerra** [mozack/vdjician#6]
When trying to compile under Mac OS 10.12 I get the following error (repeatedly, and in different places)

In file included from src/main/c/assembler2_vdj.c:15:
src/main/c/sparsehash/sparse_hash_map:94:10: fatal error: 'tr1/functional' file not found

What am I missing?

**Comment by mozack** [comment]
VDJer relies upon Google's sparsehash may have issues on Mac. If you're open to experimenting, you could try replacing the sparsehash currently used in VDJer with Google's latest version: https://github.com/sparsehash/sparsehash/

I'll try to find a Mac on which to test here, but cannot promise a quick turnaround.

**Comment by afonsoguerra** [comment]
Thanks, I'll try to install the GitHub version of sparsehash. If you think it is because of the Mac, I will also switch to Linux and have a go.

**Comment by mozack** [comment]
If you have access to a Linux machine, I'd recommend going that route.  All of our runs have been on Linux.

**Comment by afonsoguerra** [comment]
I've followed your advice and updated the sparsehash. A new error now appeared:

src/main/c/vj_filter.c:312:2: error: use of undeclared identifier 'pthread_mutex_init'
        pthread_mutex_init(&vjf_mutex, NULL);
        ^

On a more positive note, it indeed compiled without issue on a linux machine, so I'll use that for the time being.

**Comment by ionox0** [comment]
Fyi I got this same issue when running the 0.92-SNAPSHOT-with-dependencies jar
```
src/main/c/sparsehash/sparse_hash_map:94:10: fatal error: 'tr1/functional' file not found
```

I first installed the g++ compiler for mac (Sierra) through macports:

https://www.macports.org/install.php

Then ran the make file after changing this:
```
native: mktargetdir
	g++ -g -I$(SRCDIR) -I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/linux -shared -fPIC $(SRCDIR)/assembler.c -o target/libAbra.so
```
To this:
```
native: mktargetdir
	/opt/local/bin/g++-mp-4.7 -g -I$(SRCDIR) -I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/linux -shared -fPIC $(SRCDIR)/assembler.c -o target/libAbra.so
```
